# Include and run all stages
include: 
#  - .gitlab/configs/.gitlab-linter-ci.yml
  # - .gitlab/configs/.gitlab-merger-ci.yml
  - .gitlab/configs/.gitlab-envtest-ci.yml
stages:
#  - linting
  # - merging
  - automerge
