envtest:
  stage: test
  image: mcr.microsoft.com/powershell:latest

  only:
    - merge_requests

  variables:
    PRIVATE_TOKEN: $SECRET_TOKEN
    MERGE_IID: $CI_MERGE_REQUEST_IID
    APPROVAL_STATUS: $CI_MERGE_REQUEST_APPROVED

  script:
    - |
      echo "Attempting to use a docker img of unix pre-installed w/ pwsh for lighter pipelining"
      echo "Expecting a masked PRIVATE_TOKEN: $PRIVATE_TOKEN"
      echo "Expecting 54 for MERGE_IID: $MERGE_IID"
      echo "Expecting true for APPROVAL_STATUS: $APPROVAL_STATUS"

      pwsh -c 'Write-Host "If no errors, will continue by accessing from env now"'
      pwsh -c Write-Host "Expecting a masked PRIVATE_TOKEN: $env:PRIVATE_TOKEN"'
      pwsh -c Write-Host "Expecting 54 for MERGE_IID: $env:MERGE_IID"'
      pwsh -c Write-Host "Expecting true for APPROVAL_STATUS: $env:APPROVAL_STATUS"'