superlinter:
# name the stage for pipelining later
  stage: linting

# use a Docker image for super-linter (slim version for faster job execution)
  image:
    name: github/super-linter:latest
    entrypoint: [""]

# only run this job on merge-requests
  only:
    - merge_requests

# run superlinter
  script:
    - |
      /action/lib/linter.sh

# specify vars used by super-linter
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_BUILDS_DIR/$CI_PROJECT_PATH
    LINTER_RULES_PATH: .gitlab/linters          # keep all linter specific configs here
    JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json   # ^ specify ESLint's config file
    VALIDATE_JAVASCRIPT_STANDARD: "false"
