auto-merger:
  stage: merging

  tags:
    - windows

# only run this job on merge-requests
  only:
    - merge_requests

# Token and Merge IID are the only things needed
# - but knowing the approvals rn is useful too
  variables:
    PRIVATE_TOKEN: $CI_JOB_TOKEN
    MERGE_IID: $CI_MERGE_REQUEST_IID
    APPROVAL_STATUS: $CI_MERGE_REQUEST_APPROVED

# List current directory to get some bearings
  script:
    - |
      Write-Host "`nThe current approval state: $env:APPROVAL_STATUS";
      Write-Host "`nNow checking some env vars like token:`t $env:PRIVATE_TOKEN";
      Write-Host "`nIt would make sense to hide that ^ though";
      Write-Host "But can also check by making a request:"

      Write-Host "`nSince we know we're in the repository root, we can Import-Module like so:";
      Import-Module ./.gitlab/modules/GitLabAPI.psm1

      Write-Host "Making sure we imported all required variables`nProjUrl:$strProjUrl`nSession:$session";

      Write-Host "Attempting to get a list of all merge requests now";
      $MRs = Get-MergeRequests;

      Write-Host "Attempting to get a list of opened merge requests now";
      $OpenMRs = Get-MergeRequests -state "opened";

      Write-Host "`nAttempting to get current merge request (from IID)";
      Get-MergeRequests -iid $env:MERGE_IID;