superlinter:
# name the stage for pipelining later
  stage: linting

# use a Docker image for super-linter
  image:
    name: github/super-linter:latest
    entrypoint: [""]

# only run this job on merge-requests
  only:
    - merge_requests

# run superlinter
  script:
    - |
      /action/lib/linter.sh

# specify vars used by super-linter
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_BUILDS_DIR
    ANSIBLE_DIRECTORY: $CI_PROJECT_PATH
    LINTER_RULES_PATH: $CI_PROJECT_PATH/.github/linters #make sure your eslint is lacated here
    JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
    VALIDATE_JAVASCRIPT_STANDARD: "false"
