superlinter:
# name the stage for pipelining later
  stage: lint

# use a Docker image for super-linter (slim version for faster job execution)
  image:
    name: github/super-linter:slim-v4
    entrypoint: [""]

# only run this job on merge-requests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# run superlinter
  script:
    - |
      /action/lib/linter.sh

# specify vars used by super-linter
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_BUILDS_DIR/$CI_PROJECT_PATH
    LINTER_RULES_PATH: ".gitlab/linters"          # keeping linter configs here
    JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json     # ^ specifying ESLint's config
    FILTER_REGEX_EXCLUDE: (.*/assets/|.vscode/|.gitlab).*
    VALIDATE_JAVASCRIPT_STANDARD: "false"
  
# Let other job run afterwards too, even if linting (most likely) fails
  allow_failure: true
